apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-0
  labels:
    type: local
spec:
  #storageClassName: local
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elasticsearch"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-1
  labels:
    type: local
spec:
  #storageClassName: local
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elasticsearch"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-2
  labels:
    type: local
spec:
  #storageClassName: local
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elasticsearch"
