apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prom-0
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prometheus"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prom-1
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prometheus"
